// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTtC-MEdt18qDRiDnCxSXmSBkqb9waViM',
    appId: '1:743672612320:web:4899dd6a8dc26874b39785',
    messagingSenderId: '743672612320',
    projectId: 'fasum-app-23099',
    authDomain: 'fasum-app-23099.firebaseapp.com',
    databaseURL: 'https://fasum-app-23099-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-23099.appspot.com',
    measurementId: 'G-C4ZJKRXLTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1WfuHA9VV8kUegQSc8xrW_DLjvffpsOY',
    appId: '1:743672612320:android:71a36268fd172fb2b39785',
    messagingSenderId: '743672612320',
    projectId: 'fasum-app-23099',
    databaseURL: 'https://fasum-app-23099-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-23099.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj4yAQAGNAyW8f0OCQ4yd6jMDI_tcMD0I',
    appId: '1:743672612320:ios:b89ec70d5cad8170b39785',
    messagingSenderId: '743672612320',
    projectId: 'fasum-app-23099',
    databaseURL: 'https://fasum-app-23099-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-23099.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj4yAQAGNAyW8f0OCQ4yd6jMDI_tcMD0I',
    appId: '1:743672612320:ios:ca2c596c735a2639b39785',
    messagingSenderId: '743672612320',
    projectId: 'fasum-app-23099',
    databaseURL: 'https://fasum-app-23099-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-23099.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
